#!/bin/bash

echo 'apt-get update && apt-get upgrade >> /var/log/update_script.log' >> ~/apt_update.sh
echo '0 4 * * 0   root    sh ~/apt_update.sh' >> crontab

# apt_update.sh is created in _user_name_(root)
# crontab -l to check current crontabs and crontab -e to edit them