#!/bin/bash

BACKUP=/etc/.crontab_backup

if [ ! -f $BACKUP ]
then
	sudo touch $BACKUP;
	sudo chmod 666 $BACKUP;
fi
if [[ $(sudo md5sum $BACKUP | cut -d' ' -f1) == $(sudo md5sum /etc/crontab | cut -d' ' -f1) ]]
then
	echo \"crontab has not been modified\"
else
	echo \"Warning ! crontab has been modified !
	echo \"Warning ! crontab has been modified !\" | mailx -s "crontab modified" root
fi
sudo cp /etc/crontab $BACKUP