#!/bin/bash

BACKUP=/etc/.crontab_temp_backup
ORIGINAL=/etc/.crontab_temp

crontab -l > $ORIGINAL

if [[ ! -f $BACKUP && -f $ORIGINAL ]]
then
	sudo touch $BACKUP;
	sudo chmod 644 $BACKUP;
	cp $ORIGINAL $BACKUP;
	echo '0 0 * * *   root    sh /init42/scripts/04'  >	.sh_temp2
	crontab -l > .crontab_temp2
	cat .sh_temp2 >> .crontab_temp2
	cat .crontab_temp | crontab

fi

if [[ -f $ORIGINAL && -f $BACKUP ]]
	then
		if [[ $(md5sum $BACKUP | cut -d' ' -f1) == $(md5sum $ORIGINAL | cut -d' ' -f1) ]]; then
			echo \"Crontab changes checker: crontab has not been modified\"
		else
			echo \"Crontab changes checker: WARNING crontab has been modified !\"
			echo \"Crontab changes checker: WARNING crontab has been modified !\" | mail -s "Crontab is modified" root@localhost.com
			cp $ORIGINAL $BACKUP;
		fi
	else
		if [[ ! -f $ORIGINAL && -f $BACKUP ]]; then
			rm $BACKUP;
		fi
		crontab -l;
fi